from app.auth.application.exceptions.base import ApplicationError


class UserNotFoundError(ApplicationError):
    pass
